# Generated by Django 5.1 on 2024-08-14 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=200)),
                ("project_description", models.CharField(max_length=200)),
                ("funded_amount", models.IntegerField(default=0)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                ("user_address", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Validator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("validator_address", models.CharField(max_length=200)),
                ("reputation_score", models.IntegerField(default=0, max_length=200)),
                ("created_at", models.DateTimeField(verbose_name="created at")),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vote_result", models.IntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vote.project"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="vote_history",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("validator_address", models.CharField(max_length=200)),
                ("vote_date", models.DateTimeField(verbose_name="vote date")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vote.project"
                    ),
                ),
                (
                    "vote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vote.vote"
                    ),
                ),
            ],
        ),
    ]
