# Generated by Django 5.1 on 2024-08-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vote", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validator",
            name="reputation_score",
            field=models.IntegerField(default=0),
        ),
    ]
