# Generated by Django 5.1 on 2024-08-17 09:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Grant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organisation",
                    models.CharField(
                        help_text="Name of the grants organization", max_length=255
                    ),
                ),
                (
                    "program_name",
                    models.CharField(
                        help_text="Name of the grant program", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the grant program"
                    ),
                ),
                (
                    "start_fund",
                    models.DateTimeField(
                        help_text="Start date and time for the funding period"
                    ),
                ),
                (
                    "end_fund",
                    models.DateTimeField(
                        help_text="End date and time for the funding period"
                    ),
                ),
                (
                    "matching_pool",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount in the matching pool",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-start_fund"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the project", max_length=255),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the project"),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        help_text="Start date and time of the project"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(help_text="End date and time of the project"),
                ),
                (
                    "current_fund",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current amount of funding received",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_contributors",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of contributors to the project",
                    ),
                ),
                (
                    "team_members",
                    models.TextField(help_text="List of team members, comma-separated"),
                ),
                ("created_by", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(default="submitted", max_length=20)),
                (
                    "grant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="grants_project.grant",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
    ]
