# Generated by Django 5.1 on 2024-08-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grants_project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="aim",
            field=models.TextField(
                blank=True, default="", help_text="Aim of the project"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="pdf_uploaded",
            field=models.CharField(
                blank=True, default="", help_text="PDF uploaded file", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="timeline",
            field=models.TextField(
                blank=True, default="", help_text="Timeline of the project"
            ),
        ),
    ]
