# Generated by Django 5.1 on 2024-08-17 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grants_project", "0002_project_aim_project_pdf_uploaded_project_timeline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="grant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ogranisation",
                to="grants_project.grant",
            ),
        ),
    ]
