# Generated by Django 5.1 on 2024-08-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grants_project", "0003_alter_project_grant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(default="active", max_length=20),
        ),
    ]
